scriptencoding utf-8
set encoding=utf-8
" disable vi compatibility (emulation of old bugs)
set nocompatible
" use indentation of previous line
set autoindent
" use intelligent indentation for C
set smartindent
" configure tabwidth and insert spaces instead of tabs
set tabstop=4        " tab width is 4 spaces
set shiftwidth=4     " indent also with 4 spaces
set expandtab        " expand tabs to spaces
set listchars=eol:¬,tab:->,trail:~,extends:>,precedes:<
set list
syntax on
" turn line numbers on
set number
" highlight matching braces
set showmatch
set mouse-=a
